### ISSUE TITLE
Warning: Tap migration for tofuutils/tap/tofuenv points to itself, stopping recursion.

### ISSUE THREAD

**Issue by cwoollard** [tofuutils/tofuenv#56]
Homebrew is presenting the following WARNING after upgrade or clean install.

brew tap tofuutils/tap
==> Tapping tofuutils/tap
Cloning into '/opt/homebrew/Library/Taps/tofuutils/homebrew-tap'...
remote: Enumerating objects: 107, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 107 (delta 44), reused 39 (delta 11), pack-reused 0
Receiving objects: 100% (107/107), 22.93 KiB | 1.91 MiB/s, done.
Resolving deltas: 100% (44/44), done.
Tapped 2 formulae (24 files, 42.9KB).

brew install tofuenv
==> Fetching tofuutils/tap/tofuenv
==> Downloading https://github.com/tofuutils/tofuenv/archive/refs/tags/v1.0.5.tar.gz
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/308230ab939032d22db108b0065b9c195ad39b4a0233551e8933b86f966dcdfa--tofuenv-1.0.5.tar.gz
==> Installing tofuenv from tofuutils/tap
Warning: Tap migration for tofuutils/tap/tofuenv points to itself, stopping recursion.
🍺  /opt/homebrew/Cellar/tofuenv/1.0.5: 30 files, 737.1KB, built in 3 seconds
==> Running `brew cleanup tofuenv`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Warning: Tap migration for tofuutils/tap/tofuenv points to itself, stopping recursion.
Warning: Tap migration for tofuutils/tap/tofuenv points to itself, stopping recursion.

**Comment by kvendingoldo** [comment]
Fixed in https://github.com/tofuutils/homebrew-tap/pull/9
