### ISSUE TITLE
Add set up of tenv shell completion to Homebrew formula

### ISSUE THREAD

**Issue by trallnag** [tofuutils/tofuenv#63]
As of now, tenv has completion support built in. `tenv completion` can be used to generate completion scripts for various shells.

There is also a formula for tenv in Homebrew. See [here](https://formulae.brew.sh/formula/tenv).

Formulae can be used to set up completion. This is currently not done for tenv.

This is the idea: Add set up of tenv shell completion to Homebrew formula

How could it be done?

The `install` method in the [formula definition](https://github.com/Homebrew/homebrew-core/blob/master/Formula/t/tenv.rb) needs to be edited.

For the awscli I find for example this:

```ruby
rm bin.glob("{aws.cmd,aws_bash_completer,aws_zsh_completer.sh}")
bash_completion.install "bin/aws_bash_completer"
zsh_completion.install "bin/aws_zsh_completer.sh"
(zsh_completion/"_aws").write <<~EOS
  #compdef aws
  _aws () {
    local e
    e=$(dirname ${funcsourcetrace[1]%:*})/aws_zsh_completer.sh
    if [[ -f $e ]]; then source $e; fi
  }
EOS
```

[source](https://github.com/Homebrew/homebrew-core/blob/f6c18cdc1b84adae9d1e6a52317458c19a2e817a/Formula/a/awscli.rb)

**Comment by trallnag** [comment]
https://github.com/Homebrew/homebrew-core/pull/172289

**Comment by kvendingoldo** [comment]
@trallnag good idea! Thank you for MR to homebrew core!
